<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reviews')->insert([
            [
                'user_id' => 21,
                'shop_id' => 1,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 2,
                'rating' => 5,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 3,
                'rating' => 3,
                'comment' => '普通でした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 4,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 5,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 6,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 7,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 8,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 9,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 10,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 11,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 12,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 13,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 14,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 15,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 16,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 17,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 18,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 19,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 21,
                'shop_id' => 20,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 1,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 2,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 3,
                'rating' => 4,
                'comment' => 'おいしかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 4,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 5,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 6,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 7,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 8,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 9,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 10,
                'rating' => 1,
                'comment' => '微妙でした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 11,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 12,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 13,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 14,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 15,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 16,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 17,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 18,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 19,
                'rating' => 1,
                'comment' => '私の口には合いませんでした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 22,
                'shop_id' => 20,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 1,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 2,
                'rating' => 3,
                'comment' => '普通でした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 3,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 4,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 5,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 6,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 7,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 8,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 9,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 10,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 11,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 12,
                'rating' => 3,
                'comment' => '普通でした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 13,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 14,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 15,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 16,
                'rating' => 2,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 17,
                'rating' => 1,
                'comment' => '私の口には合いませんでした',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 18,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 19,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 23,
                'shop_id' => 20,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
