<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('reviews')->insert([
            [
                'user_id' => 1,
                'shop_id' => 1,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 2,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 3,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 4,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 5,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 6,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 7,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 8,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 9,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 10,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 11,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 12,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 13,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 14,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 15,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 16,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 17,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 18,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 19,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'shop_id' => 20,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 1,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 2,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 3,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 4,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 5,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 6,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 7,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 8,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 9,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 10,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 11,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 12,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 13,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 14,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 15,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 16,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 17,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 18,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 19,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'shop_id' => 20,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 1,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 2,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 3,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 4,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 5,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 6,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 7,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 8,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 9,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 10,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 11,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 12,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 13,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 14,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 15,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 16,
                'rating' => 5,
                'comment' => 'とても美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 17,
                'rating' => 4,
                'comment' => '美味しかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 18,
                'rating' => 3,
                'comment' => '普通でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 19,
                'rating' => 2,
                'comment' => 'まずかったです！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'shop_id' => 20,
                'rating' => 1,
                'comment' => '最悪でした！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
